### ISSUE TITLE
Hilfe

### ISSUE THREAD

**Issue by Kug5** [Kug5/UebenLollipop5_0#4]
Nach Bedarf soll eine Hilfe in Form von Farbigen Kugeln eingeblendet werden können

Stichpunkte:
ImageView (eine einbauen), in diese wird ein generiertes Bitmap plaziert

**Comment by Jofagi** [comment]
Bitmaps generieren klingt aber umständlich. Kann man nicht z.B. eingefärbte ● Zeichen (https://www.fileformat.info/info/unicode/char/25cf/index.htm) als Text ausgeben?

**Comment by Jofagi** [comment]
Noch eine Idee: Ziffern einfärben, damit die "kleinen Aufgaben" leichter sichtbar sind.
Beispiel: "12 + 5" hier könnte dann die 2 und 5 in rot angezeigt werden.

**Comment by Kug5** [comment]
ja klingt noch kompliziert, die Idee kam aber von jemandem der Ahnung hat. Das war Ihre erste Idee zur "Kugelhilfe". 
Sie meinte, das wird Spaß machen. Ich bin für andere Ideen aber auch offen.
